platform :ios, '10.0'

target 'Demo' do
  use_frameworks!

  pod 'CombineX', :git => 'https://github.com/cx-org/CombineX.git', :branch => 'master'
  pod 'CXFoundation', :git => 'https://github.com/cx-org/CXFoundation.git', :branch => 'master'

  pod 'CXCocoa', :path => '../'

end
